Enh testing
YunoHost-Apps/dolibarr_ynh pull request #46
Opened 2021-01-07 13:58 UTC by ericgaspar

- *Fix linter warning*
- *New permissions*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/dolibarr_ynh%20PR-NUM-%20(ericgaspar)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/dolibarr_ynh%20PR-NUM-%20(ericgaspar)/)

2021-02-02 15:27 UTC, alexAubin commented on scripts/install
>  ynh_permission_create --permission "public access" --url "/public/" --allowed "visitors"
By the way i don't know about this ... the permission id contains a space which is not really expected and will sooner or later end up causing issues.... If the purpose was to have a proper display name for the tile, then --label should be used for this. Also I don't realize what this permission corresponds to, but "public access" sounds like not appropriate from a semantic point of view ... it's more appropriate to say if it's the API for example, or the portal, or whatever this part of the app is. (because the purpose of the permission is that you can change which people are allowed, so it may or may not be effectively "public" ...)

2021-02-09 14:43 UTC, mastereur commented on scripts/install
>  ynh_permission_create --permission "public access" --url "/public/" --allowed "visitors"
Dolibarr proposes a public space even if the application remains private.
This space is used for example for a payment page.

You are right about the blank in the ID.
It is necessary to change the syntax of the function by :
ynh_permission_create --permission "public_space" --url "/public/" --allowed "visitors"

2021-02-09 16:00 UTC, mastereur requested changes

2021-02-09 16:06 UTC, mastereur requested changes
THANK YOU for the work you have done.

Looking more closely at the use of the phpversion variable, I couldn't find where it is initialized.
I guess you were inspired by the Nextcloud package which is a real treasure.
Unfortunately, currently the package is not optimal for updating a php version.
So we need to improve this point first.

2021-02-09 16:11 UTC, ericgaspar commented
The PHP variable can be found here: https://github.com/YunoHost-Apps/dolibarr_ynh/blob/57d61bc9932a4f9535c51794b9b43d3fbcff9718/scripts/_common.sh#L6

2021-02-09 17:28 UTC, ericgaspar commented
!testme

2021-02-22 17:28 UTC, merged